#query to find donors
Select 
  
  A.AGE AS Age,
  A.CITY as City,
  B.AMOUNT as Amount,
     A.GENDER as Gender,
     A.STATE,
     A.COUNTRY as Country,
     B.TRANSACTION_ID,
        CASE
        WHEN A.AGE BETWEEN 20 AND 29 THEN 20
        WHEN A.AGE BETWEEN 30 AND 39 THEN 30
        WHEN A.AGE BETWEEN 40 AND 49 THEN 40
        WHEN A.AGE BETWEEN 50 AND 59 THEN 50
        WHEN A.AGE BETWEEN 60 AND 69 THEN 60
        WHEN A.AGE BETWEEN 70 AND 79 THEN 70
        WHEN A.AGE BETWEEN 80 AND 89 THEN 80
        WHEN A.AGE BETWEEN 90 AND 99 THEN 90
        WHEN A.AGE BETWEEN 100 AND 109 THEN 100
        WHEN A.AGE BETWEEN 110 AND 119 THEN 110
        ELSE NULL end as age_category

       
from jgough2_FINAL_PROJECT.CONSTITUENT A left join jgough2_FINAL_PROJECT.TRANSACTIONS B  ON A.CONSTITUENT_ID = B.CONSTITUENT_ID left join jgough2_FINAL_PROJECT.EVENT_ATTENDEE C  ON A.CONSTITUENT_ID = C.CONSTITUENT_ID
GROUP BY CITY;








